#HSQLDBデータベース接続情報
spring.datasource.url=jdbc:hsqldb:hsql://localhost/AWSLEARNINGDB
spring.datasource.username=SA
spring.datasource.password=kazushi
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDrive
