#HSQLDBデータベース接続情報
spring.datasource.url=jdbc:hsqldb:hsql://localhost/AWSLERNINGDB
spring.datasource.username=SA
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDrive
